---

- name: get RCMCardDav release
  get_url:
    url: "https://github.com/blind-coder/rcmcarddav/releases/download/v{{ roundcube_carddav_version }}/carddav-{{ roundcube_carddav_version }}.tar.bz2"
    dest: "{{ roundcube_path }}/plugins"
  register: carddav
  when: not ansible_check_mode

- name: unarchive RCMCardDav  # noqa 503
  unarchive:
    src: "{{ roundcube_path }}/plugins/carddav-{{ roundcube_carddav_version }}.tar.bz2"
    dest: "{{ roundcube_path }}/plugins/"
    copy: no
  when: carddav.changed

- name: ensure current RCMCardDav config
  template:
    src: "plugins/carddav/config.inc.php.j2"
    dest: "{{ roundcube_path }}/plugins/carddav/config.inc.php"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_user }}"
    mode: 0640

- name: Patch RCMCardDav for Nextcloud
  patch:
    src: 0001-silently-fail-if-preset-cannot-be-loaded.patch
    dest: "{{ roundcube_path }}/plugins/carddav/carddav_discovery.php"
