---
- name: Assert that required variables set
  ansible.builtin.assert:
    that:
      - roundcube_mysql_password is defined and roundcube_mysql_password != ""
      - roundcube_des_key is defined and roundcube_des_key != ""
    fail_msg: "roundcube_mysql_password and roundcube_des_key must be set"
    success_msg: "roundcube_mysql_password and roundcube_des_key are set"

- name: Populate service facts
  ansible.builtin.service_facts:
