---
driver:
  name: docker

platforms:
  - name: debian12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ""
    volumes:
      - /var/lib/containerd
    pre_build_image: true
    cgroupns: host

provisioner:
  name: ansible
  ansible_args:
    - --diff

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
