---
driver:
  name: docker

platforms:
  - name: debian13
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    pre_build_image: true
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
