---
name: Integration
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".*"
      - ".github/**"
      - "README.md"

jobs:
  integration:
    name: Integration
    uses: systemli/github-ansible-workflow/.github/workflows/ansible-integration-workflow.yaml@24.04
    with:
      disable-apparmor-mysql: true
      distros: '[ "debian12", "debian11" ]'
